config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :hokkaido, only: [:edit, :update, :index]
  resources :hcontact
  resources :hokkaido, only: [:edit, :update, :index]
  resources :japan, only: [:edit, :update, :index]
  root 'hokkaido#index'

  get 'hokkaido/hokkaido_map'
  get 'hokkaido/hokkaido_value'
  get 'hokkaido/hokkaido_only'
  get 'japan/japan_map'
  get 'japan/japan_value'

  get 'hokkaido/version' => 'hokkaido#version'

  post 'hokkaido/update' => 'hokkaido#update'
  patch 'hokkaido/update' => 'hokkaido#update'

  get 'hokkaido/info' => 'hokkaido#info'
  post 'hokkaido/info' => 'hokkaido#info'

  get 'hokkaido/show/:id' => 'hokkaido#show'
  get 'hokkaido/move_show' => 'hokkaido#move_show'
  post 'hokkaido/move_show' => 'hokkaido#move_show'

  get 'hokkaido/dl_jiti_info' => 'hokkaido#dl_jiti_info'
  get 'hokkaido/dl_update_info' => 'hokkaido#dl_update_info'
  get 'hokkaido/dl_contact_info' => 'hokkaido#dl_contact_info'
  get 'hokkaido/dl_selection_info' => 'hokkaido#dl_selection_info'
  get 'hokkaido/dl_service_info' => 'hokkaido#dl_service_info'

  get 'hokkaido/move_edit' => 'hokkaido#move_edit'
  post 'hokkaido/move_edit' => 'hokkaido#move_edit'

  get 'hokkaido/:id/edit.js.erb' => 'hokkaido#edit'

  get 'hokkaido/dl' => 'hokkaido#dl'
  get 'hokkaido/cluster' => 'hokkaido#cluster'
end

app/controllers/hokkaido_controller.rb
class HokkaidoController < ApplicationController
  protect_from_forgery except: :edit
  @@versionLength = PaperTrail::Version.select("id").count
  def index
    @hservices = Hservice.all
    @hservices_name = @hservices.to_json(only: [:keyName ,:serviceName, :comment])
    @hservices_name_array = JSON.parse(@hservices_name)
    @versions = PaperTrail::Version.order('created_at DESC').limit(100)
    @oldVersionCount = 314
    @search = Hvalue.search(params[:search])
    @hselections = Hselection.all
    @vender = @hselections.uniq.pluck(:vender)
  end

  def edit
    @hvalues = Hvalue.all
    @hvalue = @hvalues.find(params[:id])
    @hcontact = @hvalue.hcontacts
    @hservices = Hservice.all
    @hselections = Hselection.all
    @versions = PaperTrail::Version.where('object like ? OR object_changes like ?', "%#{@hvalue.cityname}%", "%#{@hvalue.cityname}%").order('created_at DESC')
    @oldVersionCount = 314
    render layout: false
  end

  def update
    @hvalue = Hvalue.find_by(cityname: params[:hvalue][:cityname])
    if @hvalue.update_attributes(hvalue_params)
      # flash[:success] = params[:hvalue][:cityname] + "の情報を更新しました"
      redirect_to action: 'edit'
    else
      # flash[:error] = "変更に失敗しました"
      render 'edit'
    end
  end

  def info
  end

  def cluster
  end

  def dl_jiti_info
    @hvalues = Hvalue.all
    respond_to do |format|
      format.html
      format.csv { send_data @hvalues.to_csv.encode(Encoding::CP932, invalid: :replace, undef: :replace), filename: "#{Date.today}_北海道_自治体情報.csv" }
      format.xls { send_data @hvalues.to_csv(col_sep: "\t"), filename: "#{Date.today}_北海道_自治体情報.xls" }
      format.json { send_data JSON.pretty_generate(JSON.parse(@hvalues.to_json(except: [:created_at, :updated_at]))), filename: "#{Date.today}_北海道_自治体情報.json", type: :json }
    end
  end

  def dl_update_info
    @versions = Version.all
    respond_to do |format|
      format.html
      format.csv { send_data @versions.to_csv.encode(Encoding::CP932, invalid: :replace, undef: :replace), filename: "#{Date.today}_北海道_更新履歴.csv" }
      format.xls { send_data @versions.to_csv(col_sep: "\t"), filename: "#{Date.today}_北海道_更新履歴.xls" }
      format.json { send_data JSON.pretty_generate(JSON.parse(@versions.to_json)), filename: "#{Date.today}_北海道_更新履歴.json", type: :json }
    end
  end

  def dl_contact_info
    @hcontacts = Hcontact.all
    respond_to do |format|
      format.html
      format.json { send_data JSON.pretty_generate(JSON.parse(@hcontacts.to_json(except: [:created_at, :updated_at]))), filename: "#{Date.today}_北海道_連絡先.json", type: :json }
    end
  end

  def dl_selection_info
    @hselections = Hselection.all
    respond_to do |format|
      format.html
      format.json { send_data JSON.pretty_generate(JSON.parse(@hselections.to_json(except: [:created_at, :updated_at]))), filename: "#{Date.today}_北海道_サービス選択肢.json", type: :json }
    end
  end

  def dl_service_info
    @hservices = Hservice.all
    respond_to do |format|
      format.html
      format.json { send_data JSON.pretty_generate(JSON.parse(@hservices.to_json(except: [:created_at, :updated_at]))), filename: "#{Date.today}_北海道_サービス説明.json", type: :json }
    end
  end

  def hokkaido_map
    data = File.read('db/hokkaido_map.json')
    render json: data
  end

  def hokkaido_only
    data = File.read('db/hokkaido_only.json')
    render json: data
  end

  def hokkaido_value
    data = Hvalue.all
    render json: data.to_json(except: [:created_at, :updated_at])
  end

  def dl
  end

  private

  def hvalue_params
    params.require(:hvalue).permit(:cityname, :kyougi, :memo_service, :memo_kiban, :todoku, :koumu, :kokaike, :el_kyodo, :kiban, :vender, :eac, :frs, :eps, :ca, :pa, :gw, :cms, :mail, :bu, :rs, :ps, :fn, :ns, :ss, :ft, :et, :ib, :sc, :sc_op1, :sc_op2, :sc_op3, :sc_op4, :sc_op5, :sc_op6)
  end
end

app/helpers/hokkaido_helper.rb
module HokkaidoHelper
  def xeditable? object = nil
    true # Or something like current_user.xeditable?
  end
end

app/views/hokkaido/_edit.html.erb
<div class="modal-dialog">
  <div class="modal-content" style="width:1100px; margin-left: -250px;">
    <%= form_for @hvalue, url: {:action => 'update'}, html: {class: "form-horizontal center"}, remote: true do |f| %>
    <%= f.hidden_field :cityname, :value => @hvalue.cityname %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title"><%= @hvalue.cityname %></h4>
      </div>
      <div class="modal-body">
        <ul class="nav nav-tabs">
          <li class="active all-space"><a href="#tab1" data-toggle="tab">自治体情報</a></li>
          <li class="all-space"><a href="#tab2" data-toggle="tab">編集</a></li>
        </ul>
        <div id="myTabContent" class="tab-content">
          <div class="tab-pane fade in active" id="tab1">
            <div class="row">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>サービス</th>
                    <th>担当課</th>
                    <th>担当者</th>
                    <th>電話番号</th>
                    <th>mail</th>
                    <th>備考欄</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% @hcontact.each do |hcontact| %>
                    <tr>
                      <td><%= hcontact.service %></td>
                      <% if hcontact.department == "※1" %>
                      <% hcontact.department = "※電子申請(＝共同システム運用保守)は、協議会事務局（北海道）に連絡" %>
                      <% elsif hcontact.department == "※2" %>
                      <% hcontact.department = "公会計(改訂・町村会,基準・町村会)の契約窓口は北海道町村会。" %>
                      <% end %>
                      <td><%= hcontact.department %></td>
                      <td><%= hcontact.person %></td>
                      <td><%= hcontact.phone %></td>
                      <td><%= mail_to hcontact.mailAddress %></td>
                      <td><%= hcontact.memo %></td>
                      <td><%= link_to '編集', "#", class: 'btn btn-info btn-xs btn-block', onclick: "editContactModal(#{hcontact.id})" %>
                          <%= link_to "削除", hcontact, method: :delete, data: { confirm: "この連絡先を削除しますか?", id: hcontact.id }, class: 'btn btn-warning btn-xs btn-block' %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <div class="col-md-6">
                <div>
                  <p><%= @hvalue.cityname %>の備考欄</p>
                  <%= f.text_area :memo_service, :value => @hvalue.memo_service, :size => "60x15" %>
                </div>
              </div>
              <div  class="col-md-6">
                <p><%= @hvalue.cityname %>の更新履歴</p>
                <% @versions.each do |version| %>
                  <% if version.event == "update" && version.reify %>
                  <%  change = version.changeset %>
                    <%=  change[:updated_at][1].year %>年<%=  change[:updated_at][1].month %>月<%=  change[:updated_at][1].day %>日<%=  change[:updated_at][1].hour %>時<%=  change[:updated_at][1].min %>分
                    <br>
                    <a onclick="get_data(<%= version.reify.id %>)" href="#" id="<%= version.reify.cityid %>">
                      <%= version.reify.cityname %>の「<%=  @hservices.find_by(keyName: change.to_a[0][0]).serviceName %>」を
                      <%=  change.to_a[0][1][0] %>から<%=  change.to_a[0][1][1] %>に変更しました
                    </a>
                    <br>
                  <% elsif version.event == "create" %>
                    <%  change = version.changeset %>
                      <% if version.item_id > @oldVersionCount %>
                        <% time = change.to_a[10][1][1] %>
                        <%=  time.year %>年<%=  time.month %>月<%=  time.day %>日<%=  time.hour %>時<%=  time.min %>分
                        <br>
                          <%= change.to_a[0][1][1] %>の連絡先を新規作成しました
                        <br>
                    <% end %>
                  <% elsif version.event == "destroy" %>
                    <% @year = version.object[version.object.index("created_at")+12...version.object.index("created_at")+16] %>
                    <% @month = version.object[version.object.index("created_at")+17...version.object.index("created_at")+19] %>
                    <% @day = version.object[version.object.index("created_at")+20...version.object.index("created_at")+22] %>
                    <% @cityname = version.object[version.object.index("cityname")+10...version.object.index("cityid")-1] %>
                        <%=  @year %>年<%=  @month %>月<%=  @day %>日
                        <br>
                          <%= @cityname %>の連絡先を削除しました
                        <br>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="tab2">
            <p><%= @hvalue.cityname %>の契約状況を編集する</p>
            <div class="row">
              <div class="panel-group" id="accordion">
                <div  style="float:left; width: 25%;">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h4 class="panel-title">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseEditOne">
                            SC関連<br>
                            <span class="glyphicon glyphicon-chevron-up"></span>
                        </a>
                      </h4>
                    </div>
                    <div id="collapseEditOne" class="panel-collapse collapse">
                      <% @hservices.where(kibanRelation: 4).each do |i| %>
                        <div class="col-md-6">
                          <%= f.label i.serviceName, {class: 'control-label', style: "width: 85px;"}%>
                        </div>
                        <div class="col-md-6">
                          <%= f.select i.keyName, @hselections.uniq.pluck(i.keyName), {:selected => @hvalue[i.keyName]}, {class: "form-control", style: "width: 120px; height: 2.2em; background-color:transparent; text-align-last:center;"} %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div  style="float:left; width: 25%;">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h4 class="panel-title">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseEditTwo">
                            ベンダ情報<br>
                            <span class="glyphicon glyphicon-chevron-up"></span>
                        </a>
                      </h4>
                    </div>
                    <div id="collapseEditTwo" class="panel-collapse collapse">
                      <% @hservices.where(kibanRelation: 5).each do |i| %>
                        <div class="col-md-6">
                          <%= f.label i.serviceName, {class: 'control-label', style: "width: 85px;"}%>
                        </div>
                        <div class="col-md-6">
                          <%= f.select i.keyName, @hselections.uniq.pluck(i.keyName), {:selected => @hvalue[i.keyName]}, {class: "form-control", style: "width: 120px; height: 2.2em; background-color:transparent; text-align-last:center;"} %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div  style="float:left; width: 25%;">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h4 class="panel-title">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseEditThree">
                            HARP基盤関連<br>
                            <span class="glyphicon glyphicon-chevron-up"></span>
                        </a>
                      </h4>
                    </div>
                    <div id="collapseEditThree" class="panel-collapse collapse">
                      <% @hservices.where(kibanRelation: 1).each do |i| %>
                        <div class="col-md-6">
                          <%= f.label i.serviceName, {class: 'control-label', style: "width: 85px;"}%>
                        </div>
                        <div class="col-md-6">
                          <%= f.select i.keyName, @hselections.uniq.pluck(i.keyName), {:selected => @hvalue[i.keyName]}, {class: "form-control", style: "width: 120px; height: 2.2em; background-color:transparent; text-align-last:center;"} %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div  style="float:left; width: 25%;">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h4 class="panel-title">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseEditFour">
                            基盤関系なし<br>
                            <span class="glyphicon glyphicon-chevron-up"></span>
                        </a>
                      </h4>
                    </div>
                    <div id="collapseEditFour" class="panel-collapse collapse">
                      <% @hservices.where(kibanRelation: 0).each do |i| %>
                        <div class="col-md-6">
                          <%= f.label i.serviceName, {class: 'control-label', style: "width: 85px;"}%>
                        </div>
                        <div class="col-md-6">
                          <%= f.select i.keyName, @hselections.uniq.pluck(i.keyName), {:selected => @hvalue[i.keyName]}, {class: "form-control", style: "width: 120px; height: 2.2em; background-color:transparent; text-align-last:center;"} %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "変更する", :class => "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>
<script type="text/javascript">

  function editContactModal(hvalueId){
          $.get( "/hcontact/" + hvalueId + "/edit", function( data ) {
          $("#product-modal").html( data )
          $("#product-modal").modal("show")
      })
  }
  
    $('.collapse')
    .on('shown.bs.collapse', function(n){
            $(n.target)
                .parent()
                .find(".glyphicon-chevron-up")
                .toggleClass('glyphicon-chevron-up glyphicon-chevron-down');
        })
    .on('hidden.bs.collapse', function(n){
            $(n.target)
                .parent()
                .find(".glyphicon-chevron-down")
                .toggleClass('glyphicon-chevron-up glyphicon-chevron-down');
        });

</script>

app/views/hokkaido/_info.html.erb
<h1>更新履歴 (最新100件)</h1>
<ul>
  <% @versions.each do |version| %>
    <% if version.event == "update" && version.reify %> <%# ←ここでSQLが発行されてる　%>
      <%  change = version.changeset %>
        <%=  change[:updated_at][1].year %>年<%=  change[:updated_at][1].month %>月<%=  change[:updated_at][1].day %>日<%=  change[:updated_at][1].hour %>時<%=  change[:updated_at][1].min %>分
        <br>
        <a onclick="get_data(<%= version.reify.id %>)" href="#" id="<%= version.reify.cityid %>">
          <%= version.reify.cityname %>の「<%=  @hservices_name_array.find{|i| i["keyName"] == change.to_a[0][0] }["serviceName"] %>」を
          <%=  change.to_a[0][1][0] %>から<%=  change.to_a[0][1][1] %>に変更しました
        </a>
        <br>
    <% elsif version.event == "create" %>
      <%  change = version.changeset %>
        <% if version.item_id > @oldVersionCount %>
          <% time = change.to_a[10][1][1] %>
          <%=  time.year %>年<%=  time.month %>月<%=  time.day %>日<%=  time.hour %>時<%=  time.min %>分
          <br>
          <a onclick="get_data(<%= change.to_a[9][1][1] %>)" href="#" id="<%= change.to_a[1][1][1] %>">
            <%= change.to_a[0][1][1] %>の連絡先を新規作成しました
          </a>
          <br>
      <% end %>
    <% elsif version.event == "destroy" %>
      <% @year = version.object[version.object.index("created_at")+12...version.object.index("created_at")+16] %>
      <% @month = version.object[version.object.index("created_at")+17...version.object.index("created_at")+19] %>
      <% @day = version.object[version.object.index("created_at")+20...version.object.index("created_at")+22] %>
      <% @id = version.object[version.object.index("hvalue_id")+11...version.object.index("created_at")-1] %>
      <% @cityid = version.object[version.object.index("cityid")+8...version.object.index("cityid")+16] %>
      <% @cityname = version.object[version.object.index("cityname")+10...version.object.index("cityid")-1] %>
          <%=  @year %>年<%=  @month %>月<%=  @day %>日
          <br>
          <a onclick="get_data(<%= @id %>)" href="#" id="<%= @cityid %>">
            <%= @cityname %>の連絡先を削除しました
          </a>
          <br>
    <% end %>
  <% end %>
</ul>
<script type="text/javascript">
    function get_data(id){
            $.get( "/hokkaido/" + id + "/edit", function( data ) {
            $( "#product-modal" ,parent.document ).html( data )
            $("#product-modal" ,parent.document).modal("show")
        })
    }
    $(document).ready(function(){
      var cityid;
      var cityColor;
        $("a").mouseover(function(){
          cityid = $(this).attr("id")
          cityColor = $(".hokkaido."+cityid ,parent.document).css("fill")
            $(".hokkaido."+cityid ,parent.document).attr("fill", "red");
        });
        $("a").mouseout(function(){
            $(".hokkaido."+cityid ,parent.document).attr("fill", cityColor);
        });
    });
</script>

app/views/hokkaido/_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content" style="width:1100px; margin-left: -250px;">
    <%= form_for @hvalue, url: {:action => 'update'}, html: {class: "form-horizontal center"}, remote: true do |f| %>
    <%= f.hidden_field :cityname, :value => @hvalue.cityname %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title"><%= @hvalue.cityname %></h4>
      </div>
      <div class="modal-body">
        <ul class="nav nav-tabs">
          <li class="active all-space"><a href="#tab1" data-toggle="tab">自治体情報</a></li>
          <li class="all-space"><a href="#tab2" data-toggle="tab">編集</a></li>
        </ul>
        <div id="myTabContent" class="tab-content">
          <div class="tab-pane fade in active" id="tab1">
            <div class="row">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>サービス</th>
                    <th>担当課</th>
                    <th>担当者</th>
                    <th>電話番号</th>
                    <th>mail</th>
                    <th>備考欄</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <% @hcontact.each do |hcontact| %>
                    <tr>
                      <td><%= hcontact.service %></td>
                      <% if hcontact.department == "※1" %>
                      <% hcontact.department = "※電子申請(＝共同システム運用保守)は、協議会事務局（北海道）に連絡" %>
                      <% elsif hcontact.department == "※2" %>
                      <% hcontact.department = "公会計(改訂・町村会,基準・町村会)の契約窓口は北海道町村会。" %>
                      <% end %>
                      <td><%= hcontact.department %></td>
                      <td><%= hcontact.person %></td>
                      <td><%= hcontact.phone %></td>
                      <td><%= mail_to hcontact.mailAddress %></td>
                      <td><%= hcontact.memo %></td>
                      <td><%= link_to '編集', "#", class: 'btn btn-info btn-xs btn-block', onclick: "editContactModal(#{hcontact.id})" %>
                          <%= link_to "削除", hcontact, method: :delete, data: { confirm: "この連絡先を削除しますか?", id: hcontact.id }, class: 'btn btn-warning btn-xs btn-block' %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <div class="col-md-6">
                <div>
                  <p><%= @hvalue.cityname %>の備考欄</p>
                  <%= f.text_area :memo_service, :value => @hvalue.memo_service, :size => "60x15" %>
                </div>
              </div>
              <div  class="col-md-6">
                <p><%= @hvalue.cityname %>の更新履歴</p>
                <% @versions.each do |version| %>
                  <% if version.event == "update" && version.reify %>
                    <%  change = version.changeset %>
                      <% time = change.to_a[1][1][1] %>
                      <%=  time.year %>年<%=  time.month %>月<%=  time.day %>日<%=  time.hour %>時<%=  time.min %>分
                      <br>
                        <%= version.reify.cityname %>の「<%=  @hservices.find_by(keyName: change.to_a[0][0]).serviceName %>」を
                        <%=  change.to_a[0][1][0] %>から<%=  change.to_a[0][1][1] %>に変更しました
                      <br>
                  <% elsif version.event == "create" %>
                    <%  change = version.changeset %>
                      <% if version.item_id > @oldVersionCount %>
                        <% time = change.to_a[10][1][1] %>
                        <%=  time.year %>年<%=  time.month %>月<%=  time.day %>日<%=  time.hour %>時<%=  time.min %>分
                        <br>
                          <%= change.to_a[0][1][1] %>の連絡先を新規作成しました
                        <br>
                    <% end %>
                  <% elsif version.event == "destroy" %>
                    <% @year = version.object[version.object.index("created_at")+12...version.object.index("created_at")+16] %>
                    <% @month = version.object[version.object.index("created_at")+17...version.object.index("created_at")+19] %>
                    <% @day = version.object[version.object.index("created_at")+20...version.object.index("created_at")+22] %>
                    <% @cityname = version.object[version.object.index("cityname")+10...version.object.index("cityid")-1] %>
                        <%=  @year %>年<%=  @month %>月<%=  @day %>日
                        <br>
                          <%= @cityname %>の連絡先を削除しました
                        <br>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="tab2">
            <div class="row">
            <p><%= @hvalue.cityname %>の契約状況</p>
            <div class="col-md-6">
              <h4>HARP基盤関連</h4>
              <div class="field">
                <div class="form-group form-group-xs">
                  <% for i in @hservices.where(kibanRelation: 1) do %>
                    <div class="col-md-6">
                      <%= f.label i.serviceName, {class: 'control-label', style: "width: 180px;"}%>
                    </div>
                    <div class="col-md-6">
                      <%= f.select i.keyName, @hvalues.uniq.pluck(i.keyName), {:selected => @hvalue[i.keyName]}, {class: "form-control", style: "width: 180px; height: 2.2em; background-color:transparent; text-align-last:center;"} %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <h4>HARP基盤関係なし</h4>
                <div class="field">
                  <div class="form-group form-group-xs">
                  <% for i in @hservices.where(kibanRelation: 0) do %>
                    <div class="col-md-6">
                      <%= f.label i.serviceName, {class: 'control-label', style: "width: 180px;"}%>
                    </div>
                    <div class="col-md-6">
                      <%= f.select i.keyName, @hvalues.uniq.pluck(i.keyName), {:selected => @hvalue[i.keyName]}, {class: "form-control", style: "width: 180px; height: 2.2em; background-color:transparent; text-align-last:center;"} %>
                    </div>
                  <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "変更する", :class => "btn btn-primary", :onclick => "insertInfo" %>
      </div>
    <% end %>
  </div>
</div>
  <script type="text/javascript">

    function editContactModal(hvalueId){
            $.get( "/hcontact/" + hvalueId + "/edit", function( data ) {
            $("#product-modal").html( data )
            $("#product-modal").modal("show")
        })
    }
    function insertInfo(){
            $('#info' ,parent.document).load("/hcontact/info");
    }
  </script>

app/views/hokkaido/dl.html.erb
<div class="row" name="test">
    <div class="col-md-2">
        <div class="btn-group-vertical" role="group" style = "margin: 10px 0px 0px 0px;">
	    	<h3>Hvalue</h3>
	    	<h4>自治体情報</h4>
            <%= link_to "自治体情報.xls", hokkaido_dl_jiti_info_path(format: "xls"), class: "btn btn-large btn-success" %>
            <%= link_to "自治体情報.csv", hokkaido_dl_jiti_info_path(format: "csv"), class: "btn btn-large btn-warning" %>
            <%= link_to "自治体情報.json", hokkaido_dl_jiti_info_path(format: "json"), class: "btn btn-large btn-primary" %>
        </div>
    </div>
    <div class="col-md-2">
        <div class="btn-group-vertical" role="group" style = "margin: 10px 0px 0px 0px;">
	    	<h3>Hcontact</h3>
	    	<h4>自治体連絡先</h4>
            <%= link_to "自治体連絡先.json", hokkaido_dl_contact_info_path(format: "json"), class: "btn btn-large btn-primary" %>
        </div>
    </div>
    <div class="col-md-2">
        <div class="btn-group-vertical" role="group" style = "margin: 10px 0px 0px 0px;">
	    	<h3>Hservice</h3>
	    	<h4>サービス名、説明</h4>
            <%= link_to "サービス.json", hokkaido_dl_service_info_path(format: "json"), class: "btn btn-large btn-primary" %>
        </div>
    </div>
    <div class="col-md-2">
        <div class="btn-group-vertical" role="group" style = "margin: 10px 0px 0px 0px;">
	    	<h3>Hselection</h3>
	    	<h4>サービスの選択肢</h4>
            <%= link_to "選択肢.json", hokkaido_dl_selection_info_path(format: "json"), class: "btn btn-large btn-primary" %>
        </div>
    </div>
    <div class="col-md-2">
        <div class="btn-group-vertical" role="group" style = "margin: 10px 0px 0px 0px;">
	    	<h3>version</h3>
	    	<h4>更新情報</h4>
            <%= link_to "更新情報.xls", hokkaido_dl_update_info_path(format: "xls"), class: "btn btn-large btn-success" %>
            <%= link_to "更新情報.csv", hokkaido_dl_update_info_path(format: "csv"), class: "btn btn-large btn-warning" %>
            <%= link_to "更新情報.json", hokkaido_dl_update_info_path(format: "json"), class: "btn btn-large btn-primary" %>
        </div>
    </div>
    <div class="col-md-2">
        <div class="btn-group-vertical" role="group" style = "margin: 10px 0px 0px 0px;">
	    	<h3>other</h3>
	    	<h4>その他</h4>
        </div>
    </div>
</div>

app/views/hokkaido/edit.html.erb
<%= render 'edit' %>

app/views/hokkaido/edit.js.erb
$("#product-modal").html("<%= escape_javascript(render 'edit') %>")
$("#product-modal").modal("show")